# Generated by Django 3.2.3 on 2021-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UUIDStamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid_string", models.UUIDField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-datetime"],
            },
        ),
    ]
