# Generated by Django 3.2.3 on 2021-05-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uuids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuidstamp',
            old_name='uuid_string',
            new_name='uuid_obj',
        ),
    ]
